version: '3.9'
services:
  frontend:
    container_name: market_products_search_frontend
    build: ./market-products-search-frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /usr/src/app/market-products-search-frontend
    depends_on:
      backend:
          condition: service_healthy
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  # Caso utilize outra porta interna para o front, altere ela aqui também
      timeout: 10s
      retries: 5
  backend:
    container_name: market_products_search_backend
    build: ./market-products-search-backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /usr/src/app/market-products-search-backend
    environment:
      - APP_PORT=3001
      - DATABASE_URL=file:./dev.db
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5